---
development:
  cloud_name: "<%= ENV["cloudinary_development_cloud_name"] %>"
  api_key: "<%= ENV["cloudinary_development_api_key"] %>"
  api_secret: "<%= ENV["cloudinary_development_api_secret"] %>"
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: "<%= ENV["cloudinary_production_cloud_name"] %>"
  api_key: "<%= ENV["cloudinary_production_api_key"] %>"
  api_secret: "<%= ENV["cloudinary_production_api_secret"] %>"
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: "<%= ENV["cloudinary_test_cloud_name"] %>"
  api_key: "<%= ENV["cloudinary_test_api_key"] %>"
  api_secret: "<%= ENV["cloudinary_test_api_secret"] %>"
  enhance_image_tag: true
  static_image_support: false


